# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default="It's my pleasure", max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='equipment',
            field=models.CharField(default='heart', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='love', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='24hr', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='traffic',
            field=models.CharField(default='MRT', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
