# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20170607_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food1_title',
            field=models.CharField(default='ha', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='food2_title',
            field=models.CharField(default='haha', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='food3_title',
            field=models.CharField(default='hahaha', max_length=200),
            preserve_default=False,
        ),
    ]
